PATH_SRC = PREFIX .. "./src/"
PATH_LIB = PATH_SRC .. "./lua-engine/"
dofile(PATH_LIB .. "./header.lua")
PATH_GAME = PATH_SRC .. "./lua-game/"
PATH_EDITOR = PATH_SRC .. "lua-editor/"
PATH_IMAGES = PREFIX .."./images/"
PATH_SOUNDS = PREFIX .."./sounds/"
PATH_SPRITES = PATH_IMAGES .. "sprites/"
PATH_GUI_IMG = PATH_IMAGES .. "gui_elements/"
PATH_TILES = PATH_IMAGES .. "tiles/"
PATH_FONTS = PREFIX .."./fonts/"
PATH_HERO = PATH_SPRITES .. "main_hero/"
PATH_MAPS = PREFIX .."./maps/"
PATH_SObj = PATH_IMAGES .. "static_objects/"
PATH_TEXT = PREFIX .."./texts/"
PREFIX_SAVE = ERPG_Utils.get_user() .. "/.rpg/"
PATH_SAVE = PREFIX_SAVE .."./saves/"
PATH_CONFIGS = PATH_GAME .. "configs/"
